# Generated by Django 5.0.6 on 2024-05-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
